# Generated by Django 5.2 on 2025-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='psychologist_photos/'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='therapies',
            field=models.CharField(max_length=255),
        ),
    ]
