# Generated by Django 5.2 on 2025-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_psychologist_photo_alter_psychologist_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psychologist',
            old_name='is_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='psychologist',
            old_name='info',
            new_name='description',
        ),
        migrations.AddField(
            model_name='psychologist',
            name='specialization',
            field=models.CharField(default='CBT', max_length=100),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='psychologists_photos/'),
        ),
    ]
