# Generated by Django 5.2 on 2025-05-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0003_rename_is_available_psychologist_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='full_name',
            field=models.CharField(default='Psiholog Fără Nume', max_length=100),
            preserve_default=False,
        ),
    ]
