# Generated by Django 5.2 on 2025-05-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0004_psychologist_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='therapies',
        ),
    ]
