# Generated by Django 5.2 on 2025-05-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by_psychologist',
            field=models.BooleanField(default=False),
        ),
    ]
